# Generated by Django 3.1.7 on 2021-03-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhs', '0002_remove_company_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='entry_sheet',
            field=models.BooleanField(default=False, verbose_name='ES提出'),
        ),
    ]
