# Generated by Django 3.1.7 on 2021-03-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhs', '0003_company_entry_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='test',
            field=models.CharField(blank=True, choices=[('0', 'a'), ('1', 'b')], max_length=2, verbose_name='test'),
        ),
    ]
