# Generated by Django 3.1.7 on 2021-03-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhs', '0004_company_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='test',
        ),
        migrations.AlterField(
            model_name='company',
            name='system',
            field=models.CharField(blank=True, choices=[('メーカー系', 'メーカー系'), ('独立系', '独立系'), ('メーカー系', 'メーカー系')], max_length=5, verbose_name='系統'),
        ),
    ]
