# Generated by Django 3.1.7 on 2021-03-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhs', '0005_auto_20210307_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='welfare_benefits',
            field=models.CharField(blank=True, max_length=150, verbose_name='福利厚生(後から方式変えるから、[, ]で区切る。(タグとか検索機能つけたい))'),
        ),
        migrations.AddField(
            model_name='company',
            name='working_times',
            field=models.CharField(blank=True, max_length=15, verbose_name='出勤・退勤(後から方式変えるかもだけど、今は00:00~00:00)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='system',
            field=models.CharField(blank=True, choices=[('メーカー系', 'メーカー系'), ('独立系', '独立系'), ('ユーザー系', 'ユーザー系')], max_length=5, verbose_name='系統'),
        ),
    ]
