# Generated by Django 3.1.7 on 2021-03-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhs', '0006_auto_20210307_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='welfare_benefits',
            field=models.TextField(blank=True, max_length=150, verbose_name='福利厚生(後から方式変えるから、[, ]で区切る。(タグとか検索機能つけたい))'),
        ),
    ]
