# Generated by Django 3.1.7 on 2021-03-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhs', '0007_auto_20210307_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='impression',
            field=models.TextField(blank=True, max_length=50, verbose_name='感想'),
        ),
    ]
